// =============================================================================
// pddi/intercept.h -- one door into every call the game makes to its renderer
// =============================================================================
//
// WHY
//   The game draws everything through Radical's renderer, PDDI, and only its
//   Xbox 360 backend (xnContext, xnTexture, xnShader...) calls Microsoft's
//   D3D (docs/findings/08). Two parts of the port need to sit on those calls:
//     - the frame tracer (pddi/trace.cpp): logs them, for research
//     - the native renderer (native/): mirrors them now ("shadow mode"), and
//       replaces them later
//   Both go through this layer, so they can work at the same time.
//
// HOW
//   The recompiler emits each game function as `__imp__sub_XXXXXXXX` (the
//   body) plus `sub_XXXXXXXX`, a WEAK alias of it. Every call goes through
//   `sub_...`: direct calls by name, virtual calls through a lookup table
//   filled from the same symbols. intercept.cpp defines a strong `sub_...` for
//   each function listed in functions.inc (generated by
//   tools/gen_pddi_table.py), so every call lands there first.
//
//   Per call, a wrapper:
//     1. tells the tracer (only while a frame is being traced)
//     2. calls the function's HANDLER if one is installed, else the original
//     3. after xnDisplay::SwapBuffers only: runs the end-of-frame listeners
//   With no handler and no trace, step 2 is a direct call of the original:
//   the cost is two relaxed atomic loads.
//
// A HANDLER gets the original function too. A "shadow" handler looks at the
// arguments, calls `original(ctx, base)`, and looks at the result. A
// "replacement" handler does the work itself and never calls it.
// =============================================================================

#pragma once

#include <atomic>
#include <cstdint>

#include <rex/ppc/context.h>
#include <rex/ppc/func.h>

namespace pddi {

// kFn_<ADDRESS>: an index per intercepted function, in table order.
enum FnId : uint16_t {
#define PDDI_METHOD(hex, name) kFn_##hex,
#define PDDI_D3D(hex, name) kFn_##hex,
#define PDDI_VTABLE(hex, name)
#include "functions.inc"
#undef PDDI_METHOD
#undef PDDI_D3D
#undef PDDI_VTABLE
  kFnCount
};

struct FnInfo {
  uint32_t address;  // guest address
  const char* name;  // e.g. "xnContext::BeginFrame", "xnContext::v56", "d3d_8230AA30"
};
extern const FnInfo kFns[kFnCount];

// xnDisplay::SwapBuffers: where one frame ends and the next begins
// (findings/07 and 08).
inline constexpr FnId kSwapBuffers = kFn_82433510;

// The renderer class whose vtable is at `vtable` ("xnContext", ...), or null.
const char* ClassOfVtable(uint32_t vtable);

// -----------------------------------------------------------------------------
// Handlers
// -----------------------------------------------------------------------------

using Handler = void (*)(PPCContext& ctx, uint8_t* base, PPCFunc* original);

// Installs (or with nullptr removes) the handler of one function. Any thread;
// calls already running keep the handler they started with.
void SetHandler(FnId fn, Handler handler);

// -----------------------------------------------------------------------------
// End-of-frame listeners
// -----------------------------------------------------------------------------

// Called on the game's main thread right after each xnDisplay::SwapBuffers
// returns: the frame the game just finished is complete.
using FrameListener = void (*)(void* user);

void AddFrameEndListener(FrameListener listener, void* user);
// After this returns the listener is not running and won't run again (it
// waits for a call in progress to finish), so `user` may be destroyed.
void RemoveFrameEndListener(FrameListener listener, void* user);

}  // namespace pddi
