// =============================================================================
// main.cpp -- program entry point
// =============================================================================
//
// There's deliberately almost nothing here. REX_DEFINE_APP expands to the
// platform's real main() (or WinMain on Windows), which creates our app
// class and runs ReXGlue's startup sequence:
//
//   1. open a window + Vulkan renderer
//   2. build the fake Xbox 360 (memory, kernel, file system...)
//   3. load default.xex into guest memory
//   4. start a guest thread at the XEX entry point (0x82300BA0), which calls
//      straight into the recompiled C++ in generated/default/
//
// Customization happens in crash_mom_app.h, not here.
// =============================================================================

// Generated by codegen: PPCImageConfig (where the code/image live in guest
// memory) and the table mapping every guest function address -> C++ function.
#include "generated/default/crash_mom_init.h"

#include "crash_mom_app.h"

REX_DEFINE_APP(crash_mom, CrashMomApp::Create)
